#!/usr/bin/env python3
"""Bundle FiT implementation modules into single Hub-ready Python files (NiT-XL style)."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable, List, Tuple

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC = REPO_ROOT / "src" / "diffusers"
OUT_TRANSFORMER = SRC / "models" / "transformers" / "fit_transformer_2d.py"
OUT_SCHEDULER = SRC / "schedulers" / "scheduling_fit_improved.py"

HEADER = """\
# Copyright 2026 The HuggingFace Team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

\"\"\"Self-contained FiT Hub module (generated by scripts/bundle_fit_hub_modules.py).\"\"\"

"""

DIFFUSERS_STUB = """
try:
    from diffusers.configuration_utils import ConfigMixin, register_to_config
    from diffusers.models.modeling_utils import ModelMixin
except Exception:  # pragma: no cover
    class ConfigMixin:
        def register_to_config(self, **kwargs):
            if not hasattr(self, "_config"):
                self._config = {}
            self._config.update(kwargs)

        @property
        def config(self):
            return self._config

    def register_to_config(func):
        return func

    class ModelMixin(nn.Module):
        pass
"""


def _strip_header(text: str) -> str:
    text = re.sub(r"^# Copyright.*?\n\n", "", text, count=1, flags=re.DOTALL)
    text = re.sub(r"^# Modified from.*?\n\n", "", text, count=1, flags=re.DOTALL)
    return text.lstrip("\n")


def _strip_relative_imports(text: str, local_stems: Iterable[str]) -> str:
    lines = []
    for line in text.splitlines():
        if re.match(r"from \.+[\w.]+ import", line):
            continue
        lines.append(line)
    text = "\n".join(lines)
    text = re.sub(
        r"try:\n(?:[^\n]*\n)*?except ImportError:\n(?:[^\n]*\n)*?\n",
        "",
        text,
    )
    return text


def _collect_imports(chunks: List[str]) -> Tuple[List[str], List[str]]:
    import_lines: List[str] = []
    bodies: List[str] = []
    seen = set()
    for chunk in chunks:
        chunk_lines = chunk.splitlines()
        body_lines: List[str] = []
        for line in chunk_lines:
            if re.match(r"^(from|import)\s", line):
                if line not in seen:
                    seen.add(line)
                    import_lines.append(line)
            else:
                body_lines.append(line)
        bodies.append("\n".join(body_lines).strip())
    return import_lines, bodies


def _bundle(files: List[Path], local_stems: List[str], *, add_diffusers_stub: bool = False) -> str:
    raw_chunks = [_strip_header(path.read_text(encoding="utf-8")) for path in files]
    cleaned = [_strip_relative_imports(chunk, local_stems) for chunk in raw_chunks]
    import_lines, bodies = _collect_imports(cleaned)

    # Remove training-only init_from_ckpt hooks from bundled transformer.
    merged_body = "\n\n".join(bodies)
    merged_body = re.sub(
        r"try:\n(?:[^\n]*\n)*?except ImportError:\n(?:[^\n]*\n)*?\n",
        "",
        merged_body,
    )
    merged_body = re.sub(
        r"        if pretrain_ckpt is not None:\n            init_from_ckpt\(self, pretrain_ckpt, ignore_keys, verbose=True\)\n",
        "",
        merged_body,
    )

    parts = [HEADER.rstrip()]
    if import_lines:
        parts.append("\n".join(import_lines))
    if add_diffusers_stub:
        parts.append(DIFFUSERS_STUB.strip())
    parts.append(merged_body.strip())
    return "\n\n".join(parts) + "\n"


def bundle_transformer() -> Path:
    files = [
        SRC / "models/transformers/fit_model_utils.py",
        SRC / "models/transformers/norms.py",
        SRC / "models/transformers/rope.py",
        SRC / "models/transformers/fit_modules.py",
        SRC / "models/transformers/transformer_fit.py",
    ]
    text = _bundle(
        files,
        ["fit_model_utils", "norms", "rope", "fit_modules", "transformer_fit", "eval_utils"],
        add_diffusers_stub=True,
    )
    OUT_TRANSFORMER.write_text(text, encoding="utf-8")
    return OUT_TRANSFORMER


def bundle_scheduler() -> Path:
    files = [
        SRC / "schedulers/improved_diffusion/diffusion_utils.py",
        SRC / "schedulers/improved_diffusion/gaussian_diffusion.py",
        SRC / "schedulers/improved_diffusion/respace.py",
        SRC / "schedulers/improved_diffusion/fit_improved_sampler.py",
    ]
    text = _bundle(
        files,
        ["diffusion_utils", "gaussian_diffusion", "respace", "fit_improved_sampler"],
    )
    OUT_SCHEDULER.write_text(text, encoding="utf-8")
    return OUT_SCHEDULER


def main() -> None:
    transformer_path = bundle_transformer()
    scheduler_path = bundle_scheduler()
    print(f"Wrote {transformer_path}")
    print(f"Wrote {scheduler_path}")


if __name__ == "__main__":
    main()
